/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainersRouteImport } from './routes/trainers'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as IndexRouteImport } from './routes/index'

const TrainersRoute = TrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classes': typeof ClassesRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/trainers': typeof TrainersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classes': typeof ClassesRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/trainers': typeof TrainersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classes': typeof ClassesRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/trainers': typeof TrainersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/classes' | '/contact' | '/pricing' | '/trainers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/classes' | '/contact' | '/pricing' | '/trainers'
  id: '__root__' | '/' | '/classes' | '/contact' | '/pricing' | '/trainers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassesRoute: typeof ClassesRoute
  ContactRoute: typeof ContactRoute
  PricingRoute: typeof PricingRoute
  TrainersRoute: typeof TrainersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainers': {
      id: '/trainers'
      path: '/trainers'
      fullPath: '/trainers'
      preLoaderRoute: typeof TrainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassesRoute: ClassesRoute,
  ContactRoute: ContactRoute,
  PricingRoute: PricingRoute,
  TrainersRoute: TrainersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
